"""empty message

Revision ID: 4fc7908d4ed3
Revises: None
Create Date: 2016-10-25 23:14:54.958876

"""

# revision identifiers, used by Alembic.
revision = '4fc7908d4ed3'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=32), nullable=False))
    op.drop_index('mob', table_name='users')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'comp_register')
    op.drop_column('users', 'gender')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', mysql.VARCHAR(length=6), nullable=False))
    op.add_column('users', sa.Column('comp_register', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('member_since', mysql.DATETIME(), nullable=True))
    op.create_index('mob', 'users', ['mob'], unique=True)
    op.drop_column('users', 'city')
    ### end Alembic commands ###
