"""empty message

Revision ID: 87ce1569a6dc
Revises: 4fc7908d4ed3
Create Date: 2016-10-26 11:33:40.291754

"""

# revision identifiers, used by Alembic.
revision = '87ce1569a6dc'
down_revision = '4fc7908d4ed3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    ### end Alembic commands ###
