"""empty message

Revision ID: 9676187b0ac6
Revises: None
Create Date: 2016-10-28 00:55:27.334610

"""

# revision identifiers, used by Alembic.
revision = '9676187b0ac6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('complete', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'complete')
    ### end Alembic commands ###
